---
permalink: install/concept_multiple_paths_to_an_array_lun_can_be_used_to_distribute_load.html 
sidebar: sidebar 
keywords: multiple, paths, array, lun, used, distribute, load, commands 
summary: 특정 LUN에 대한 입출력 요청은 사용 가능한 최적화된 모든 LUN 경로를 통해 분산될 수 있습니다. 이는 여러 경로를 사용할 수 있지만 특정 LUN에 대한 I/O 요청이 최적화된 단일 경로를 통해서만 전송된 이전 릴리스와 다릅니다. 
---
= 스토리지 LUN에 대한 여러 경로를 사용하여 로드를 분산할 수 있습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 LUN에 대한 입출력 요청은 사용 가능한 최적화된 모든 LUN 경로를 통해 분산될 수 있습니다. 이는 여러 경로를 사용할 수 있지만 특정 LUN에 대한 I/O 요청이 최적화된 단일 경로를 통해서만 전송된 이전 릴리스와 다릅니다.

지정된 LUN에 대한 입출력 요청을 여러 경로에 분산하면 다음과 같은 이점이 있습니다.

* 사용 가능하고 최적화된 모든 경로를 최대한 활용하여 효율성이 향상되었습니다
* 여러 경로에 대한 로드 밸런싱으로 성능이 향상되었습니다


예를 들어 Active-Active 스토리지에서는 해당 LUN에 대해 사용 가능한 4개의 타겟 포트 모두를 통해 해당 LUN에 대한 입출력 요청을 분산할 수 있습니다. 비대칭형 Active-Active 스토리지 LUN의 경우 지정된 LUN에 대해 최적화된 모든 경로를 통해 입출력 요청을 분산할 수 있습니다.



== 지정된 LUN에 대한 여러 경로에 대한 로드 밸런싱을 확인하는 명령입니다

다음 명령을 실행하여 특정 LUN에 대한 여러 경로에 대한 로드 분포를 볼 수 있습니다.

* ``storage disk show -disk <LUN name>`` 지정된 스토리지 LUN에 대해 사용 가능한 경로에 대한 입출력 로드 분포를 표시합니다.
* ``storage path show-by-initiator -array-name <array name>`` 지정된 스토리지에 접속된 ONTAP 시스템의 모든 이니시에이터 포트에 대한 입출력 로드 분포를 표시합니다.
* ``storage path show -by-target -array-name <array name>`` 지정된 스토리지 배열의 모든 타겟 포트에 대한 입출력 로드 분포를 표시합니다.

