---
permalink: install/concept_formulas_for_calculating_array_lun_size_considering_checksum_type.html 
sidebar: sidebar 
keywords: formulas, calculate, array, lun, size, checksum, type, usable, capacity, snapshot, reserve, maximum 
summary: 체크섬 유형을 포함한 많은 요소가 스토리지 LUN의 가용 용량에 영향을 미칩니다. 공식을 사용하여 지정된 크기의 스토리지 LUN에 사용할 수 있는 용량을 계산하거나 원하는 스토리지 용량을 제공하기 위해 스토리지 LUN의 크기를 계산할 수 있습니다. 
---
= 체크섬 유형을 기반으로 스토리지 LUN 크기를 계산하는 공식입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
체크섬 유형을 포함한 많은 요소가 스토리지 LUN의 가용 용량에 영향을 미칩니다. 공식을 사용하여 지정된 크기의 스토리지 LUN에 사용할 수 있는 용량을 계산하거나 원하는 스토리지 용량을 제공하기 위해 스토리지 LUN의 크기를 계산할 수 있습니다.

체크섬 유형을 포함한 여러 요소는 _가용 용량_ 양에 필요한 스토리지 LUN의 크기에 영향을 줍니다. 사용 가능 용량은 스토리지에 사용할 수 있는 공간의 양입니다.

다음 표에는 필요한 스토리지 LUN 크기를 계산하는 방법이 나와 있습니다.

[cols="2*"]
|===
| 알고 있는 경우... | 찾을 내용... 


 a| 
어레이 LUN의 크기입니다
 a| 
스토리지에 사용 가능한 용량(사용 가능 용량)입니다. 모든 요소에 필요한 공간의 양을 고려해야 합니다.



 a| 
어레이 LUN에서 원하는 스토리지 크기입니다
 a| 
필요한 어레이 LUN의 크기입니다. 필요한 저장 공간과 다른 요소에 필요한 공간을 고려해야 합니다.

|===
[NOTE]
====
이러한 공식에서 2TB는 2TiB 또는 2199023255552바이트를 의미하며, ONTAP가 측정값을 계산하는 방식에 따라 2097.152 GnaB 또는 2.097 Suspird B입니다.

====


== 가용 용량을 계산하는 공식입니다

어레이 LUN의 크기를 알고 있는 경우 다음 공식을 사용하여 어레이 LUN의 스토리지에 사용할 수 있는 용량을 확인할 수 있습니다. 이 수식은 스냅숏 예비 공간을 고려합니다.

* y는 스토리지에 사용할 수 있는 용량입니다.
* N은 스토리지 LUN의 총 용량입니다.


[cols="2*"]
|===
| 체크섬 유형 | 수식 


 a| 
BCS - 2TB 미만의 스토리지 LUN
 a| 
n x{0.875 x 0.9 x 0.99 x (1 - 스냅숏 예비 공간)} = Y



 a| 
BCS - - 2TB 이상의 스토리지 LUN
 a| 
n x{0.875 x 0.9 x 0.998 x (1 - Snapshot reserve)} = Y



 a| 
AZCS - 2TB 미만의 스토리지 LUN
 a| 
n x{0.984 x 0.9 x 0.99 x (1 - Snapshot reserve)} = Y



 a| 
AZCS - 2TB 이상의 스토리지 LUN
 a| 
n x{0.984 x 0.9 x 0.998 x (1 - Snapshot reserve)} = Y

|===


== 예 1: Calculations_with_a Snapshot reserve

다음 예에서는 스토리지 LUN의 총 용량이 4GB이고 볼륨 스냅샷 예비 공간이 기본적으로 Data ONTAP 8.1.1에 설정되어 있습니다(5%).

다음은 2TB 미만의 스토리지 LUN에 대한 예입니다.

[cols="2*"]
|===
| 체크섬 유형 | 수식 


 a| 
BCS(스토리지 LUN 2TB 미만)
 a| 
4 x {0.875 x 0.9 x 0.99 x 0.95} = 2.96GB의 저장 공간



 a| 
AZCS(스토리지 LUN 2TB 미만)
 a| 
4 x {0.984 x 0.9 x 0.99 x 0.95} = 3.33GB의 저장 가능 공간

|===


== 필요한 최대 스토리지 LUN 크기를 계산하는 공식입니다

원하는 스토리지 용량을 얻는 데 필요한 스토리지 LUN 용량을 알고 있는 경우 다음 공식을 사용하여 LUN에 공간이 필요한 요소를 고려하여 필요한 총 스토리지 LUN 크기를 결정할 수 있습니다.

* y는 스토리지 LUN에서 원하는 공간의 정확한 크기입니다.
* 스냅샷 복사본을 사용하는 경우 스냅샷 예약률이 적용됩니다.


다음은 2TB 미만의 스토리지 LUN에 대한 예입니다.

[cols="2*"]
|===
| 체크섬 유형 | 수식 


 a| 
BCS(스토리지 LUN 2TB 미만)
 a| 
Y ÷{0.875 x 0.9 x 0.99 x (1-Snapshot reserve)} = 필요한 실제 용량입니다



 a| 
AZCS(스토리지 LUN 2TB 미만)
 a| 
Y ÷{0.984 x 0.9 x 0.99 x (1-Snapshot reserve)} = 필요한 실제 용량

|===


== 예 2: Calculations_with_Snapshot 예비 공간

이 예에서 볼륨 스냅숏 예비 공간은 Data ONTAP 8.1.1의 기본 설정(5%)입니다.

다음은 2TB 미만의 스토리지 LUN에 대한 예입니다.

[cols="2*"]
|===
| 체크섬 유형 | 수식 


 a| 
BCS(스토리지 LUN 2TB 미만)
 a| 
10GB ÷ {0.875 x 0.9 x 0.99 x 0.95} = 필요한 실제 용량 13.5GB



 a| 
AZCS(스토리지 LUN 2TB 미만)
 a| 
10GB ÷ {0.984 x 0.9 x 0.99 x 0.95} = 필요한 실제 용량 12.05GB

|===


== 예제 3: Calculations_without_Snapshot 예비 공간

스토리지에 10GB의 가용 용량이 필요합니다. 다음 예제는 스냅샷 복사본을 사용하지 않을 때의 실제 어레이 LUN 크기 계산을 보여줍니다.

다음은 2TB 미만의 스토리지 LUN에 대한 예입니다.

[cols="2*"]
|===
| 체크섬 유형 | 수식 


 a| 
BCS(스토리지 LUN 2TB 미만)
 a| 
10GB ÷ {0.875 x 0.9 x 0.99} = 필요한 실제 용량 12.8GB



 a| 
AZCS(스토리지 LUN 2TB 미만)
 a| 
10GB ÷ {0.984 x 0.9 x 0.99} = 필요한 실제 용량 11.41GB

|===