---
permalink: install/concept_example_of_cascading_zoning_and_host_group_configuration_errors.html 
sidebar: sidebar 
keywords: example, cascade, zone, host, group, configuration, errors, troubleshoot 
summary: 영역 정의에서 오류가 발생하면 호스트 그룹 정의에 영향을 줄 수 있으며 그 반대의 경우도 마찬가지입니다. LUN이 경로 위에 표시되지 않으면 조닝 및 호스트 그룹 구성 오류를 모두 확인해야 합니다. 
---
= 계단식 조닝 및 호스트 그룹 구성 오류의 예
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
영역 정의에서 오류가 발생하면 호스트 그룹 정의에 영향을 줄 수 있으며 그 반대의 경우도 마찬가지입니다. LUN이 경로 위에 표시되지 않으면 조닝 및 호스트 그룹 구성 오류를 모두 확인해야 합니다.

구성 순서는 다음과 같습니다.

. 존 정의가 스위치에 생성되었습니다.
+
ONTAP 시스템의 FC 이니시에이터 포트 0a에 대한 WWPN이 영역 정의에 포함되었습니다. 하지만 FC 이니시에이터 포트 0c에 대한 WWPN이 존 정의에 들어오고 있었습니다.

. 호스트 그룹이 스토리지 시스템에 생성되었습니다.
+
FC 이니시에이터 포트 0a에 대한 WWPN을 선택했습니다. 이 WWPN은 사용 가능한 유일한 WWPN이므로 0a에 대한 WWPN이 0c가 아니라 0c에 대한 WWPN인지 확실하지 않음).

. ONTAP에서는 FC 이니시에이터 포트를 통해 어레이 LUN을 조사했으며, 0c를 넘는 어레이 LUN이 표시될 것으로 예상됩니다.
+
하지만 영역 정의와 호스트 그룹 정의 모두에 FC 이니시에이터 포트 0a의 WWPN이 잘못 포함되어 있으므로 0c를 통해 어레이 LUN이 없었습니다.

+
[NOTE]
====
명령을 사용하여 `storage array config show` 스토리지 LUN 정보를 확인했습니다.

====
. 예상되는 이니시에이터 위에 LUN이 표시되지 않기 때문에 문제 해결을 시작합니다.


조닝 및 호스트 그룹 구성을 모두 확인해야 하지만 다음 절차 중 먼저 시작하는 절차는 중요하지 않습니다. 호스트 그룹에서 항목을 먼저 수정할지, 아니면 먼저 조닝에서 먼저 시작하는지에 따라 다른 메시지가 표시될 수 있습니다.



== 먼저 조닝을 확인하여 문제를 해결하십시오

. ONTAP 시스템의 영역 정의를 확인하십시오.
+
FC 이니시에이터 포트 0a에 대한 WWPN이 두 개 있고, 여기에 0c에 대한 WWPN이 있는 영역이 없습니다.

. 잘못된 영역 정의를 수정하고 활성화합니다.
+
[NOTE]
====
을 실행할 때는 이니시에이터 포트를 통해 어레이 LUN을 볼 수 `storage array config show`없습니다.

====
. 어레이로 이동하여 FC 이니시에이터 포트 0c에 대한 WWPN을 포함하도록 호스트 그룹을 재구성합니다.
+
이제 0c에 대한 WWPN이 활성화된 영역 정의에 있으므로 0c에 대한 WWPN이 스토리지 배열의 호스트 그룹 구성에 있는 선택 목록에 표시됩니다.

. ONTAP 시스템에서 를 실행하여 `storage array config show` FC 이니시에이터 포트를 통해 스토리지 LUN을 검사하여 스토리지 LUN이 0c를 통해 표시되는지 확인합니다.




== 먼저 호스트 그룹을 확인하여 문제를 해결합니다

. ONTAP 시스템 콘솔에서 -0c가 누락된 어댑터의 WWPN을 실행한 `storage show adapteradapter#``다음 이 예에 기록합니다.
. 스토리지 어레이로 이동하여 적은 WWPN을 호스트 그룹 선택 목록에 있는 WWPN과 비교하여 예상된 FC 이니시에이터 포트의 WWPN이 나열되어 있는지 확인합니다.
+
필요한 WWPN이 표시되지 않으면 의도한 이니시에이터가 영역 정의에 있지 않습니다.

. 스토리지 어레이에서 호스트 그룹의 WWPN을 수정할 수 있는 경우 표시된 WWPN을 기록해 둔 WWPN으로 수정할 수 있습니다.
+
[NOTE]
====
스토리지 배열에서 호스트 그룹의 WWPN을 수정할 수 없는 경우 영역 정의를 수정한 후 호스트 그룹 정의를 수정해야 합니다.

====
+
조닝이 아직 수정되지 않았기 때문에 아직 예정했던 이니시에이터에서 LUN을 볼 수 없습니다.

. 스위치로 이동하여 잘못된 WWPN을 올바른 FC 포트 이니시에이터로 교체한 다음 존 정의를 활성화합니다.
. 프로세스의 이전 호스트 그룹 정의에서 WWPN을 수정할 수 없는 경우 스토리지 어레이로 이동하여 FC 이니시에이터 포트 0c에 대한 WWPN을 포함하도록 호스트 그룹을 다시 구성하십시오.
+
이제 0c에 대한 WWPN이 활성화된 영역 정의에 있으므로 0c에 대한 WWPN이 스토리지 배열의 호스트 그룹 구성에 있는 선택 목록에 표시됩니다.

. ONTAP 시스템에서 를 실행하여 `storage array config show` FC 이니시에이터 포트를 통해 스토리지 LUN을 검사하여 스토리지 LUN이 0c를 통해 표시되는지 확인합니다.
+
이제 FC 이니시에이터 포트를 통해 LUN에 액세스할 수 있습니다.


