---
permalink: install/concept_target_port_utilization_policy_settings.html 
sidebar: sidebar 
keywords: target, port, utilization, policy, settings, output, examples, array 
summary: ONTAP는 타겟 포트에서 입출력 대기열이 꽉 찼거나, 명령이 시간 초과되거나, HBA 리소스가 소진되는 등의 리소스 경합 이벤트를 감지할 수 있습니다. 
---
= 대상 포트 사용률 정책 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 타겟 포트에서 입출력 대기열이 꽉 찼거나, 명령이 시간 초과되거나, HBA 리소스가 소진되는 등의 리소스 경합 이벤트를 감지할 수 있습니다.

지정된 스토리지 대상 포트에서 이러한 이벤트를 감지한 경우 명령을 사용하여 타겟 포트 사용률 정책을 설정할 수 `storage array port modify` 있습니다.

다음 표에서는 타겟 포트와 연결된 두 가지 사용률 정책을 설명합니다.

|===
| 정책 | 설명 


 a| 
* 정상 *
 a| 
ONTAP는 지정된 스토리지 타겟 포트에서 타겟 포트 리소스 경합을 감지하면 타겟 포트의 대기열 길이를 줄이고 타겟 포트에 대한 입출력을 조절합니다. 이 모드에서 대상 포트 대기열 깊이의 감소는 각 대상 포트 리소스 경합 이벤트에 대한 * defer * 정책보다 작습니다. 이후 대상 포트 대기열 깊이의 증가는 * defer * 정책보다 빠릅니다. * 정상 * 은 기본 정책입니다.



 a| 
* 연기 *
 a| 
ONTAP는 지정된 스토리지 타겟 포트에서 타겟 포트 리소스 경합을 감지하면 타겟 포트의 대기열 길이를 줄이고 타겟 포트에 대한 입출력을 조절합니다. 이 모드에서는 각 대상 포트 리소스 경합 이벤트에 대한 대상 포트 대기열 깊이의 감소가 * normal * 정책보다 큽니다. 이후 대상 포트 대기열 깊이의 증가는 * normal * 사용률 정책보다 느립니다.

|===


== 스토리지 타겟 포트 사용률 정책을 보고 수정하는 출력 예

다음 명령을 실행하면 스토리지 대상 포트와 연결된 타겟 포트 사용률 정책이 표시됩니다.

[listing]
----
vgv3170_jon::> storage array port show -wwnn 2703750270235
        Array Name: HITACHI_DF600F_1
              WWNN: 2703750270235
              WWPN: 2703750270235
   Connection Type: fabric
       Switch Port: vgbr300s89:9
        Link Speed: 4 GB/s
   Max Queue Depth: 1024
Utilization Policy: defer
                              LUN                                        Link
Node              Initiator  Count   IOPS    KB/s    %busy    %waiting   Errs
----------------  ---------  -----  ------  ------  -------  ----------  ----
     vgv3170f54a         0a      2       50   1956       85           0     0
     vgv3170f54b         0a      2      350  15366      100          40     0
----
기본적으로 지정된 스토리지 대상 포트에 대한 I/O 정책은 * normal * 입니다. 다음 명령을 실행하여 포트와 연결된 I/O 정책을 수정할 수 있습니다.

[listing]
----
vgv3070f50ab::> storage array port modify -wwpn 50014380025d1509 -utilization-policy ?



normal      This policy aggressively competes for target port resources, in effect competing with other hosts.
             (normal)

defer      	This policy does not aggressively compete for target port resources, in effect deferring to other hosts.

vgv3070f50ab::> storage array port modify -wwpn 50014380025d1509 -utilization-policy defer
1 record updated.
----