---
permalink: install/concept_available_lun_security_methods.html 
sidebar: sidebar 
keywords: available, lun, security, methods, port-level, storage, array, dedicate, ontap 
summary: 다양한 LUN 보안 방법을 사용하면 특정 어레이 LUN에 액세스할 수 있는 호스트를 지정할 수 있습니다. 포트 수준 보안 또는 LUN 보안 제품을 사용하거나 ONTAP 시스템에서 사용할 전용 스토리지를 사용할 수 있습니다. 
---
= 사용 가능한 LUN 보안 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다양한 LUN 보안 방법을 사용하면 특정 어레이 LUN에 액세스할 수 있는 호스트를 지정할 수 있습니다. 포트 수준 보안 또는 LUN 보안 제품을 사용하거나 ONTAP 시스템에서 사용할 전용 스토리지를 사용할 수 있습니다.



== 포트 레벨 보안

포트 레벨 보안을 사용하여 특정 호스트에 대한 어레이 LUN만 제공할 수 있습니다. 그러면 이 포트가 해당 호스트 전용이 됩니다.

모든 스토리지 어레이가 포트 수준 보안을 지원하는 것은 아닙니다. 일부 스토리지 시스템은 기본적으로 모든 포트에 모든 LUN을 제공하며 특정 호스트에 대한 LUN의 표시 여부를 제한할 수 있는 방법을 제공하지 않습니다. 이러한 스토리지의 경우 LUN 보안 제품을 사용하거나 스토리지 시스템을 ONTAP 시스템에 전용으로 지정해야 합니다. 스토리지 배열 설명서를 참조하여 스토리지 배열이 포트 수준 보안을 지원하는지 확인해야 합니다.



== LUN 보안 제품

LUN 보안 제품을 사용하여 동일한 포트에 조닝된 호스트를 제어할 수 있으므로 해당 포트를 통해 특정 스토리지 LUN만 액세스할 수 있습니다. 이렇게 하면 다른 호스트가 다른 호스트에서 마스킹하여 동일한 스토리지 LUN을 액세스할 수 없습니다.



== ONTAP 전용 스토리지 시스템을 사용합니다

스토리지 어레이를 ONTAP 시스템용으로 전용할 수 있습니다. 이 경우 ONTAP 시스템 이외의 호스트는 스토리지 어레이에 접속되지 않습니다.

조닝과 LUN 보안을 모두 사용하여 ONTAP 시스템에 대한 보호 및 이중화를 추가해야 합니다.

LUN 보안 방법을 따르는 것 외에도 공급업체의 스토리지 어레이에 대한 LUN 보안에 대한 추가 세부 정보도 확인해야 합니다. 일부 스토리지 어레이는 ONTAP 시스템에서만 사용해야 합니다.

* 관련 정보 *

https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["타사 스토리지를 위한 FlexArray 가상화 구축"]

https://docs.netapp.com/us-en/ontap-flexarray/implement-e-series/index.html["NetApp E-Series 스토리지를 위한 FlexArray 가상화 구축"]
