---
permalink: install/concept_back_end_configuration_errors_detected_by_ontap_commands.html 
sidebar: sidebar 
keywords: back-end, configuration, errors, detected, ontap, commands, output, examples 
summary: 스토리지 오류 표시 명령은 스토리지 LUN 레벨에서 일반적인 백엔드 구성 오류에 대한 세부 정보를 제공합니다. 또한 스토리지 디스크 오류 표시 및 스토리지 디스크 표시 오류 명령을 사용하여 오류를 볼 수도 있습니다. 
---
= ONTAP 명령으로 백엔드 구성 오류가 감지되었습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 `storage errors show` 명령은 스토리지 LUN 레벨에서 일반적인 백엔드 구성 오류에 대한 세부 정보를 제공합니다. 또한, 및 명령을 사용하여 오류를 볼 수도 `storage disk error show` `storage disk show -errors` 있습니다.

스토리지 LUN에서 작동하도록 ONTAP를 구성하려면 먼저 이러한 명령을 통해 식별된 백엔드 구성 오류를 수정해야 합니다.

[NOTE]
====
명령은 어레이 LUN과 관련된 오류 세부 정보를 제공하지만 `storage errors show` `storage disk error show` , 및 `storage disk show -errors` 명령은 스토리지 LUN 및 디스크와 관련된 오류 세부 정보를 제공할 수 있습니다.

====
구성에 있는 장치가 함께 작동하지 못하게 하는 백엔드 구성 오류가 있는 경우 이 `storage array config show` 명령은 오류 세부 정보를 얻기 위해 storage error show 를 실행하도록 지시합니다.



== 백엔드 구성 오류 목록입니다

 `storage errors show` `storage disk error show`, 및 `storage disk show -errors` 명령을 사용하면 다음과 같은 백엔드 구성 오류를 식별할 수 있습니다.

* 어레이 LUN에 대한 경로가 2개 미만입니다.
* 어레이 LUN에 대한 모든 경로는 동일한 스토리지 컨트롤러에 있습니다.
* 두 개의 스토리지 LUN이 동일한 LUN ID로 표시됩니다.
* LDEV가 표시되는 모든 타겟 포트에서 동일한 LDEV의 LUN ID가 일치하지 않습니다.
* 스토리지 LUN이 ONTAP 최대 LUN 크기를 초과합니다.
* 스토리지 LUN이 ONTAP 최소 LUN 크기를 충족하지 않습니다.
* 스토리지 LUN의 블록 크기가 잘못되었습니다.
* 액세스 LUN이 ONTAP에 제공됩니다.




== 백엔드 구성 오류를 표시하는 출력 예

 `storage errors show`출력은 스토리지 어레이별로 그룹화됩니다(ONTAP 시스템 뒤에 스토리지 어레이가 두 개 이상 있는 경우). 해당되는 경우 스토리지 LUN의 이름 및 UID(고유 식별자)가 표시됩니다.

다음 출력 예는 하나의 오류 유형, 즉 어레이 LUN에 대한 하나의 경로만 보여 줍니다. ONTAP에는 어레이 LUN에 대한 두 개의 경로가 필요하므로 이 오류가 발생합니다.

[NOTE]
====
어레이 LUN에 대한 4개의 경로가 클러스터 구성용으로 지원됩니다.

====
다음 예에서는 어레이 LUN에 단일 경로만 구성되어 있으므로 명령에서 반환되는 오류를 보여 `storage errors show` 줍니다.

[listing]
----

systemf47ab::*> storage errors show
DGC-1.51         onepath           DGC-1.51 (6006016044d03500ae553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.54         onepath           DGC-1.54 (6006016044d03500b4553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.55         onepath           DGC-1.55 (6006016044d03500b6553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.56         onepath           DGC-1.56 (6006016044d03500b8553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.57         onepath           DGC-1.57 (6006016044d03500ba553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.58         onepath           DGC-1.58 (6006016044d03500bc553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
----
다음 예제는 명령을 통해 반환되는 비슷한 오류를 `storage disk show -errors` 보여줍니다.

[listing]
----

systemf47ab::*> storage disk show -errors
DGC-1.2          onepath           DGC-1.2 (6006016044d03500e0720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.3          onepath           DGC-1.3 (6006016044d03500e2720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.4          onepath           DGC-1.4 (6006016044d03500e3720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.5          onepath           DGC-1.5 (6006016044d03500e4720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.6          onepath           DGC-1.6 (6006016044d03500e5720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.7          onepath           DGC-1.7 (6006016044d03500e6720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
----