---
permalink: install/concept_dependency_between_zone_and_host_group_definitions.html 
sidebar: sidebar 
keywords: dependency, between, zone, host, group, definitions, common, errors, cascading, effect 
summary: 영역 정의에서 오류가 발생하면 호스트 그룹 정의를 재구성하고 반대로 변경해야 할 수 있습니다. 
---
= 존과 호스트 그룹 정의 간의 종속성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
영역 정의에서 오류가 발생하면 호스트 그룹 정의를 재구성하고 반대로 변경해야 할 수 있습니다.

영역 정의를 구성할 때는 ONTAP 시스템에 있는 FC 이니시에이터 포트의 WWPN과 해당 영역에 대한 스토리지 어레이 포트 WWPN 또는 WWNN이라는 두 개의 포트를 지정합니다. 마찬가지로 ONTAP 시스템용 호스트 그룹이 스토리지 어레이에 구성되어 있을 때 호스트 그룹의 구성원이 될 FC 이니시에이터 포트의 WWPN이 지정됩니다.

일반적인 구성 순서는 다음과 같습니다.

. 영역 정의를 구성합니다.
. 선택 목록에서 ONTAP 시스템에 있는 FC 이니시에이터 포트의 WWPN을 선택하여 스토리지 시스템에서 호스트 그룹을 구성합니다.
. 스토리지 LUN을 포트에 제공합니다.


그러나 호스트 그룹은 영역 정의 전에 구성되기도 하므로 스토리지 배열의 호스트 그룹 구성에서 WWPN을 수동으로 입력해야 합니다.



== 일반적인 오류

ONTAP 출력에서 ONTAP 시스템의 FC 이니시에이터 포트는 어댑터 번호로 식별됩니다. 예를 들어, 0a, 0b, 0c, 0d, 온보드 포트가 있는 모델의 경우 등과 같은 작업을 수행할 수 있습니다. WWPN은 스위치 GUI 및 스토리지 어레이 GUI에 표시됩니다. WWPN은 Long 이고 16진수 형식이므로 다음과 같은 오류가 자주 발생합니다.

[cols="2*"]
|===
| WWPN을 지정하는 방법입니다 | 일반적인 오류입니다 


 a| 
관리자는 WWPN에 입력합니다
 a| 
입력 오류가 발생했습니다.



 a| 
스위치에서 WWPN을 자동으로 검색합니다
 a| 
선택 목록에서 잘못된 FC 이니시에이터 포트 WWPN을 선택했습니다.

|===
[NOTE]
====
ONTAP 시스템, 스위치 및 스토리지 어레이를 케이블로 연결하면 스위치가 ONTAP 시스템 및 스토리지 어레이 포트의 WWPN을 자동으로 검색합니다. 그러면 WWPN을 스위치 GUI의 선택 목록에서 사용할 수 있으므로 WWPN을 입력하는 대신 각 영역 구성원의 WWPN을 선택할 수 있습니다. 입력할 때 오류가 발생할 가능성을 줄이려면 스위치에서 WWPN을 검색하는 것이 좋습니다.

====


== 오류의 계단식 효과

패브릭 연결 구성 관련 문제를 해결할 때 명백한 첫 번째 단계는 조닝을 올바르게 구성했는지 확인하는 것입니다. 호스트 그룹과 존 정의 간의 관계를 고려하는 것도 중요합니다. 문제를 해결하려면 구성 프로세스 중에 오류가 발생한 위치에 따라 존 정의와 호스트 그룹 정의를 모두 재구성해야 할 수 있습니다.

스위치가 WWPN을 자동으로 검색하고 영역 정의를 먼저 구성하면 스토리지 어레이의 LUN에 액세스하는 데 사용되는 FC 이니시에이터 포트의 WWPN이 스토리지 배열 GUI의 호스트 그룹 구성 선택 목록에 자동으로 전파됩니다. 따라서 조닝 오류도 스토리지 호스트 그룹 선택 목록에 전파됩니다. 선택 목록은 ONTAP 시스템에 표시되는 짧은 FC 이니시에이터 포트 레이블 대신 긴 16진수 WWPN을 표시합니다(예: 0a, 0b 등). 따라서 나열될 것으로 예상되는 WWPN이 존재하지 않는지 확인하는 것은 간단하지 않습니다.

다음 표에서는 특정 오류의 영향을 보여 줍니다.

[cols="3*"]
|===
| 스위치의 영역 정의 | 스토리지 배열의 호스트 그룹 구성 | ONTAP 출력의 증상 


 a| 
존 정의의 FC 이니시에이터 포트가 잘못되었습니다. 이로 인해 잘못된 FC 이니시에이터 포트 WWPN이 호스트 그룹 구성으로 전파되었습니다.
 a| 
원하는 WWPN이 아니라 선택 목록에 표시된 FC 이니시에이터 포트의 WWPN을 선택했습니다.
 a| 
예상되는 LUN이 표시되는 FC 이니시에이터 포트 위에 스토리지 LUN이 표시되지 않습니다.



 a| 
존 정의에는 올바른 FC 이니시에이터 포트가 포함되어 있습니다.
 a| 
다음 중 하나 때문에 호스트 그룹 정의의 WWPN이 잘못되었습니다.

* 잘못된 WWPN을 선택했습니다.
* 존 정의를 구성하기 전에 호스트 그룹을 수동으로 구성했고 FC 이니시에이터 포트의 WWPN에 입력할 때 입력 오류가 발생했습니다.

 a| 

|===