---
permalink: install/concept_rules_for_sharing_an_fc_initiator_port_with_multiple_target_ports.html 
sidebar: sidebar 
keywords: rules, share, fc initiator, port, multiple, target, connect, storage, arrays 
summary: ONTAP 시스템의 FC 이니시에이터 포트를 별도의 스토리지 어레이에 있는 최대 4개의 타겟 포트에 연결할 수 있습니다. FC 이니시에이터 포트를 여러 타겟과 공유하면 사용되는 FC 이니시에이터 포트의 수를 최소화하려는 경우에 유용합니다. 
---
= FC 이니시에이터 포트를 여러 타겟 포트와 공유하기 위한 규칙입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 시스템의 FC 이니시에이터 포트를 _separate_storage 어레이에 있는 최대 4개의 타겟 포트에 연결할 수 있습니다. FC 이니시에이터 포트를 여러 타겟과 공유하면 사용되는 FC 이니시에이터 포트의 수를 최소화하려는 경우에 유용합니다.

액세스되는 타겟 포트를 기반으로 FC 이니시에이터에 다른 논리 디바이스 세트를 제공할 수 있는 경우 스토리지에서 _SITE_STORAGE 스토리지의 최대 4개의 타겟 포트에 FC 이니시에이터 포트를 연결할 수도 있습니다.

FC 이니시에이터 포트를 통해 표시할 수 있는 어레이 LUN 개수에 제한이 있습니다. 이러한 제한은 릴리스에 따라 다릅니다.



== FC 이니시에이터 포트가 _separate_storage 어레이의 여러 타겟 포트에 접속되는 경우의 규칙입니다

이 구성에 대한 규칙은 다음과 같습니다.

* 모든 스토리지 어레이는 동일한 공급업체 모델 제품군의 모델이어야 합니다.
+
동일한 제품군의 스토리지 시스템은 동일한 성능 및 페일오버 특성을 공유합니다. 예를 들어, 같은 제품군의 구성원은 모두 액티브-액티브 페일오버를 수행하거나 모두 액티브-패시브 페일오버를 수행합니다. 스토리지 어레이 제품군을 확인하는 데 둘 이상의 요소를 사용할 수 있습니다. 예를 들어, 다른 특성이 동일하더라도 아키텍처가 다른 스토리지 어레이는 다른 제품군에 속할 수 있습니다.

* MetroCluster 구성에서는 단일 FC 이니시에이터 포트를 여러 개의 타겟 포트에 연결하는 것이 지원됩니다.
* 단일 FC 이니시에이터 포트는 여러 스토리지 어레이에 있는 최대 4개의 타겟 포트에 연결할 수 있습니다.
* 같은 FC 이니시에이터 포트가 여러 타겟 포트에 액세스하고 있더라도 각 FC Initiator-Target 포트 쌍이 별도의 존(1:1)에 있어야 합니다.




== FC 이니시에이터 포트가 _SITE_스토리지 시스템의 여러 타겟 포트에 접속된 경우의 규칙입니다

이 구성은 LUN 마스킹, 표시 또는 호스트 그룹 기능을 통해 액세스되는 타겟 포트를 기반으로 동일한 FC 이니시에이터에 다른 LUN 그룹을 표시할 수 있는 스토리지 시스템에서만 사용할 수 있습니다.

일부 스토리지 시스템은 액세스되는 타겟 포트에 따라 FC 이니시에이터에 서로 다른 논리 디바이스 세트를 제공할 수 있습니다. 이러한 유형의 스토리지 어레이에서는 동일한 FC 이니시에이터를 여러 호스트 그룹에 포함할 수 있습니다. 이 기능을 사용하는 스토리지 어레이에서는 각 FC 이니시에이터 포트가 동일한 스토리지 시스템의 여러 어레이 타겟 포트에 액세스할 수 있으며, 각 타겟 포트는 FC 이니시에이터에 서로 다른 LUN 그룹을 제공할 수 있습니다. 스토리지 시스템에서 동일한 FC 이니시에이터를 여러 호스트 그룹에 포함할 수 있는지 확인하려면 스토리지 시스템 설명서를 참조하십시오.

이 구성의 규칙은 다음과 같습니다.

* 단일 FC 이니시에이터 포트는 스토리지 시스템의 최대 4개의 타겟 포트에 연결할 수 있습니다.
* MetroCluster 구성에서는 단일 FC 이니시에이터 포트를 여러 개의 타겟 포트에 연결하는 것이 지원됩니다.
* 같은 FC 이니시에이터가 여러 타겟 포트에 액세스하는 경우에도 각 FC Initiator-Target 포트 쌍이 별도의 존(1:1)에 있어야 합니다.


* 관련 정보 *

https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["타사 스토리지를 위한 FlexArray 가상화 구축"]

https://docs.netapp.com/us-en/ontap-flexarray/implement-e-series/index.html["NetApp E-Series 스토리지를 위한 FlexArray 가상화 구축"]

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["패브릭 연결 MetroCluster 설치 및 구성"]
