---
permalink: install/concept_stages_of_implementation_for_a_system_using_array_luns.html 
sidebar: sidebar 
keywords: stages, implementation, system, use, array, luns, back end, front end 
summary: 시스템에서 스토리지 시스템의 LUN을 사용하는 구성을 구현하는 경우 백엔드 구축과 프런트엔드 구축의 두 단계로 구성됩니다. 구성을 계획할 때 각 단계의 높은 수준의 작업을 이해하는 데 도움이 됩니다. 
---
= 스토리지 LUN을 사용하는 시스템의 구현 단계입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템에서 스토리지 시스템의 LUN을 사용하는 구성을 구현하는 경우 백엔드 구축과 프런트엔드 구축의 두 단계로 구성됩니다. 구성을 계획할 때 각 단계의 높은 수준의 작업을 이해하는 데 도움이 됩니다.



== 1단계: 백엔드 구축

백 엔드 구현을 설정하는 데에는 ONTAP 소프트웨어를 설치할 수 있는 단계까지 스토리지 어레이가 있는 ONTAP 시스템을 설정하는 데 필요한 모든 작업이 포함됩니다.

백 엔드 구현을 설정하는 작업은 다음과 같습니다.

. 스토리지 LUN 생성 및 포맷
. 포트 할당
. 케이블 연결
. 조닝 스위치(해당되는 경우)
. ONTAP에서 특정 어레이 LUN을 ONTAP 시스템에 할당합니다
. ONTAP에서 네트워크에 ONTAP 시스템을 설정하기 위한 정보를 제공합니다
. ONTAP 소프트웨어를 설치하는 중입니다


ONTAP 시스템과 함께 디스크 쉘프를 주문한 경우, ONTAP 소프트웨어는 공장에서 설치됩니다. 이러한 구성에서는 루트 볼륨을 생성하고 라이센스 및 ONTAP 소프트웨어를 설치할 필요가 없습니다.

ONTAP 시스템을 디스크 쉘프 없이 주문하는 경우, 클러스터를 설정하기 전에 ONTAP를 구성해야 합니다.



== 2단계: 프런트엔드 구현

프런트엔드 구축을 설정하는 작업은 디스크를 사용하는 시스템과 동일하며 다음을 포함합니다.

* 모든 프로토콜(NAS, FC 또는 둘 다)에 대해 ONTAP 시스템 구성
* SnapVault, SnapMirror, SnapValidator 및 Snapshot 복사본과 같은 ONTAP 기능 구성
* 볼륨 및 애그리게이트 생성
* 테이프에 대한 NDMP 덤프를 포함한 데이터 보호 설정

