---
permalink: install/concept_prerequisites_to_reconfiguring_an_array_lun_on_the_storage_array.html 
sidebar: sidebar 
keywords: prerequisites, reconfigure, array. lun, storage, array 
summary: '스토리지 LUN이 이미 특정 ONTAP 시스템에 할당된 경우(ONTAP를 통해) ONTAP 스토리지 관리자가 스토리지 시스템에서 스토리지 LUN을 재구성하기 전에 스토리지 LUN에 쓴 정보를 제거해야 합니다.' 
---
= 스토리지 시스템에서 스토리지 LUN을 재구성하기 위한 사전 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 LUN이 이미 특정 ONTAP 시스템에 할당된 경우(ONTAP를 통해) ONTAP 스토리지 관리자가 스토리지 시스템에서 스토리지 LUN을 재구성하기 전에 스토리지 LUN에 쓴 정보를 제거해야 합니다.

스토리지 시스템이 스토리지 LUN을 ONTAP에 제공할 때 ONTAP는 스토리지 LUN에 대한 정보(예: 해당 크기)를 수집하고 해당 정보를 스토리지 LUN에 씁니다. ONTAP은 스토리지 LUN에 기록한 정보를 동적으로 업데이트할 수 없습니다. 따라서 스토리지 어레이 관리자가 스토리지 LUN을 재구성하기 전에 ONTAP를 사용하여 스토리지 LUN의 상태를 _unused_로 변경해야 합니다. ONTAP 관점에서 스토리지 LUN은 사용되지 않습니다.

스토리지 LUN의 상태를 미사용 상태로 변경하는 동안 ONTAP은 다음을 수행합니다.

* 스토리지 LUN에 대한 입출력 작업을 종료합니다
* 스토리지 LUN에서 RAID 구성 정보 레이블 및 영구 예약을 제거하여 스토리지 LUN을 ONTAP 시스템에서 소유하지 않게 합니다


이 프로세스가 완료되면 스토리지 LUN에 ONTAP 정보가 남아 있지 않습니다.

스토리지 LUN의 상태가 Unused로 변경된 후 다음을 수행할 수 있습니다.

* ONTAP에 대한 스토리지 LUN 매핑을 제거하고 다른 호스트에서 스토리지 LUN을 사용할 수 있도록 설정합니다.
* 스토리지 LUN의 크기를 조정하거나 구성을 변경합니다.


크기 또는 구성이 변경된 후 ONTAP에서 스토리지 LUN을 다시 사용하려면 스토리지 LUN을 ONTAP에 다시 제공하고 스토리지 LUN을 ONTAP 시스템에 다시 할당해야 합니다. ONTAP는 새 스토리지 LUN 크기 또는 구성을 알고 있습니다.
