---
permalink: install/reference_volume_set_addressing_is_inconsistent.html 
sidebar: sidebar 
keywords: volume, set, address, inconsistent, show, message, troubleshoot, problem, resolution 
summary: ONTAP는 스토리지에 대해 설정된 경로 전체에서 일관되지 않은 LUN ID를 감지할 수 있습니다. 볼륨 세트 주소 지정이 설정된 스토리지 시스템의 경우 LUN이 매핑된 포트의 설정이 일치하지 않는 문제가 LUN ID가 일치하지 않는 문제 중 하나입니다. 
---
= 볼륨 세트 주소 지정이 일관되지 않습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 스토리지에 대해 설정된 경로 전체에서 일관되지 않은 LUN ID를 감지할 수 있습니다. 볼륨 세트 주소 지정이 설정된 스토리지 시스템의 경우 LUN이 매핑된 포트의 설정이 일치하지 않는 문제가 LUN ID가 일치하지 않는 문제 중 하나입니다.

예를 들어 EMC Symmetrix 스토리지 시스템에서 LUN이 매핑되는 채널 디렉터 포트의 볼륨 세트 주소 지정 매개 변수 설정이 일치하지 않으면 LUN 불일치 오류가 발생합니다.



== 저장 장치 오류가 메시지를 표시합니다

[listing]
----

EMC-1.128 (4849544143484920443630303035323430303132): This Array LUN is using multiple LUN IDs.  Only one LUN ID per serial number is supported.
----


== 설명

오류 메시지를 발생시킬 수 있는 여러 구성 오류가 있습니다. 이 설명은 볼륨 세트 주소 지정이 일관되지 않게 설정된 경우 이 메시지가 표시되는 것에 관한 것입니다.

ONTAP은 LUN이 매핑된 포트에서 볼륨 세트 주소 지정 매개 변수의 일관되지 않은 설정이 있는지 명시적으로 확인합니다. 설정이 다른 경우 ONTAP는 이를 출력 및 EMS 메시지에서 LUN ID 불일치로 `storage errors show` 보고합니다.

[NOTE]
====
ONTAP는 볼륨 세트 주소 지정이 예상대로 구성되지 않은 경우 사용자에게 경고하지 않습니다. LUN이 매핑된 채널 디렉터 포트에서 구성이 일치하지 않는 경우에만 경고합니다.

====


== 문제 해결 및 문제 해결

명령이 특정 오류 메시지를 표시하고 스토리지가 EMC Symmetrix인 경우 `storage errors show` 다음 중 하나를 수행하면 문제가 볼륨 세트 주소 지정 불일치로 인한 것인지 여부를 확인할 수 있습니다.

* ONTAP에서 식별된 스토리지 LUN에 대해 를 실행합니다 `storage disk show -disk` .
+
이 명령은 스토리지 LUN에 대한 모든 경로와 각 경로에 할당된 LUN ID를 표시합니다.

* 스토리지 배열에서 식별된 LUN이 매핑되는 채널 디렉터 포트에 대한 볼륨 세트 주소 지정 설정을 확인합니다.


설정이 일관되지 않은 것으로 확인되면 스토리지 배열의 구성 문제를 해결하고 두 채널 디렉터 포트의 매개 변수를 ONTAP에서 요구하는 설정으로 설정해야 합니다.

* 관련 정보 *

https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["타사 스토리지를 위한 FlexArray 가상화 구축"]
