---
permalink: install/reference_commands_for_checking_back_end_configuration.html 
sidebar: sidebar 
keywords: commands, check, back-end, configuration 
summary: 백엔드 구성 오류를 포함하여 여러 ONTAP 명령을 통해 스토리지 배열 구성에 대한 정보를 제공합니다. 이러한 명령은 설치 확인 및 문제 해결 시 특히 유용합니다. 
---
= 백엔드 구성을 확인하는 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백엔드 구성 오류를 포함하여 여러 ONTAP 명령을 통해 스토리지 배열 구성에 대한 정보를 제공합니다. 이러한 명령은 설치 확인 및 문제 해결 시 특히 유용합니다.

이 `storage array config show` 명령은 설치 확인 중에 사용하는 첫 번째 명령입니다. 또한 시스템이 예상대로 작동하지 않거나 오류 메시지가 표시되는 경우 사용하는 첫 번째 명령입니다.

설치 확인 및 문제 해결에 특히 유용한 명령은 다음 표에 나와 있습니다.

|===
| 명령 | 설명 


 a| 
`storage array config show`
 a| 
스토리지 어레이 LUN을 사용한 ONTAP 시스템 구축 시 스토리지 어레이 레벨에서 백엔드 디바이스 구성에 대한 정보를 제공합니다. 이 명령은 스토리지 배열이 클러스터에 접속하는 방식을 보여 줍니다. ONTAP에서 어레이 LUN과 스토리지 어레이를 사용하는 ONTAP 시스템이 제대로 작동하지 않는 문제를 감지하면 에서 `storage array config show` 를 실행하여 `storage errors show` 오류에 대한 세부 정보를 얻을 수 있습니다.

이 명령은 구성이 의도한 대로 설정되었는지 확인하는 데도 유용합니다. 예를 들어, 출력을 확인하여 원하는 스토리지 LUN 그룹의 수가 생성되었는지 확인할 수 있습니다.



 a| 
`storage array show -name array_name`
 a| 
클러스터에 표시되는 모든 스토리지 어레이 또는 지정한 스토리지 배열에 대한 정보를 표시합니다. 표시된 스토리지 LUN 수가 시스템 용량을 초과하는 경우 오류 텍스트 필드에 ONTAP에서 검색할 수 없는 LUN 수가 표시됩니다. 특히 메모리 부족 시스템에서 이 문제를 주의해야 합니다.



 a| 
`storage path quiesce`
 a| 
특정 경로의 특정 스토리지 LUN에 대한 입출력을 일시적으로 일시 중단합니다. 이 경로는 재부팅 시 또는 를 실행하여 다시 `storage path resume`활성화됩니다. 일부 스토리지 시스템에서는 스토리지 LUN을 제거하거나 이동하려면 일정 기간 동안 입출력을 중단해야 합니다.

[NOTE]
====
이 `storage path quiesce` 명령은 IBM DS 스토리지 어레이와 함께 사용할 수 없습니다.

====


 a| 
`storage path resume`
 a| 
I/O가 다시 흐르기 시작할 수 있도록 합니다. 이것은 정지의 역함수 입니다. 이 `storage path resume` 명령은 주로 하드웨어 유지 보수(예: 케이블 또는 GBIC 풀)에 사용되거나 스토리지 LUN에 대한 경로가 실수로 정지된 후에 사용됩니다. 경로를 정지한 후에 항상 이 명령을 실행할 필요는 없습니다. 예를 들어, ONTAP는 새로 매핑된 어레이 LUN을 검색할 수 있습니다.



 a| 
`storage array show`
 a| 
이름, 공급업체, 모델 등 클러스터에 표시되는 스토리지 시스템에 대한 정보를 표시합니다. 페일오버 유형을 선택합니다.



 a| 
`storage disk show`
 a| 
 `storage disk show`매개 변수를 사용하지 않고 입력하면 모든 디스크 및 어레이 LUN에 대한 다음이 표시됩니다. 이름, 사용 가능 크기, 컨테이너 유형, 위치, 애그리게이트, 소유자입니다.  `storage disk show`디스크 이름 또는 스토리지 LUN 이름을 매개 변수로 입력하면 상태(할당됨 또는 할당되지 않음), 소유자 및 스토리지 LUN 경로 등 개별 디스크 또는 어레이 LUN에 대한 세부 정보가 표시됩니다. 출력은 스토리지 LUN에 대한 정보, 스토리지 LUN에 대한 경로 정보 및 스토리지 LUN과 관련된 모든 오류의 세 부분으로 나뉩니다.



 a| 
`storage disk show -errors _**_`
 a| 
매개 변수를 사용하여 입력하면 `storage disk show` ``-errors` 디스크 및 어레이 LUN 레벨의 구성 오류에 대한 세부 정보가 표시됩니다. 명령 출력이 명령의 출력과 비슷하지만 `storage disk error show` 에서는 `storage disk show -errors` 노드, 클러스터 및 베이 위치와 같은 매개 변수를 기준으로 출력을 필터링할 수 있는 추가 옵션을 제공합니다.



 a| 
`storage disk error show`
 a| 
디스크 및 스토리지 LUN 레벨에서 백엔드 구성 오류에 대한 자세한 내용은 에 나와 있습니다.  `storage disk error`스토리지 LUN 이름을 매개 변수로 사용하여 show를 입력하면 지정된 스토리지 LUN과 관련된 구성 오류에 대한 세부 정보가 표시됩니다. 스토리지 배열에서 작동하도록 ONTAP를 구성하기 전에 이러한 오류를 수정해야 합니다.



 a| 
`storage errors show`
 a| 
어레이 LUN 레벨에서 ONTAP 시스템과 스토리지 어레이가 함께 작동하지 않도록 하는 백엔드 구성 오류에 대한 자세한 내용은 에 나와 있습니다. 스토리지 배열에서 작동하도록 ONTAP를 구성하기 전에 에서 식별된 오류를 수정해야 `storage errors show` 합니다.

[NOTE]
====
 `storage errors show`명령을 실행하면 디스크 구성 오류에 대한 정보가 제공되지 않습니다. 디스크 및 어레이 LUN 구성 오류에 대한 정보를 보려면 `storage disk show -errors` 명령이나 `storage disk error show` 명령을 사용합니다.

====
|===