---
permalink: install/reference_terminology_comparison_between_storage_array_vendors.html 
sidebar: sidebar 
keywords: terminology, comparison, between, storage, array, vendors 
summary: 서로 다른 스토리지 어레이 공급업체마다 유사한 개념을 설명하기 위해 서로 다른 용어를 사용하는 경우가 있습니다. 또는 동일한 용어가 어레이 공급업체마다 다를 수 있습니다. 
---
= 스토리지 공급업체 간 용어 비교
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
서로 다른 스토리지 어레이 공급업체마다 유사한 개념을 설명하기 위해 서로 다른 용어를 사용하는 경우가 있습니다. 또는 동일한 용어가 어레이 공급업체마다 다를 수 있습니다.

다음 표에서는 일반적인 공급업체 용어 간의 매핑을 보여 줍니다.

|===
| 기간 | 공급업체 | 정의 


 a| 
호스트 그룹입니다
 a| 
부족했습니다
 a| 
스토리지 배열의 포트에 대한 호스트 액세스를 지정할 수 있는 구성 엔티티입니다. LUN에 액세스하려는 ONTAP 시스템의 FC 이니시에이터 포트 WWN을 식별합니다. 프로세스는 공급업체에 따라 다르며, 동일한 공급업체의 스토리지 모델마다 다를 수 있습니다.



 a| 
HP XP 를 참조하십시오
 a| 



| 스토리지 그룹  a| 
EMC CX, EMC VNX
 a| 



| 호스트 정의  a| 
3PAR를 참조하십시오
 a| 



| 호스트  a| 
3PAR, HP EVA, HP XP, Hitachi
 a| 



 a| 



| 패리티 그룹  a| 
Hitachi, HP XP입니다
 a| 
정의된 RAID 레벨을 구성하는 백엔드 디스크 배열입니다.



 a| 
RAID 그룹
 a| 
ONTAP, EMC CX, EMC VNX
 a| 



| 디스크 그룹입니다  a| 
HP EVA(HP
 a| 
가상 디스크를 생성할 수 있는 스토리지 풀을 구성하는 물리 디스크 집합입니다.



 a| 
패리티 세트, RAID 세트
 a| 
3PAR를 참조하십시오
 a| 
패리티 보호 _chunklets_ 그룹. (청크 조각 은 물리적 디스크에 인접한 256MB 블록입니다.)



 a| 
 a| 
|  


| 클러스터  a| 
ONTAP
 a| 
ONTAP에서는 여러 노드가 리소스를 대규모 가상 서버로 풀링하고 클러스터 전체에 작업을 분산할 수 있도록 하는 노드 그룹입니다.



 a| 
| Hitachi, HP XP입니다  a| 
호스트가 연결하는 포트가 포함된 스토리지 배열의 하드웨어 구성 요소입니다.



 a| 
 a| 
|  


| 컨트롤러  a| 
ONTAP
 a| 
ONTAP 운영 체제를 실행하고 백엔드 스토리지 어레이와 상호 작용하는 스토리지 시스템의 구성 요소입니다. 컨트롤러는 헤드 또는 CPU 모듈이라고도 합니다.



 a| 
| Hitachi, HP EVA, HP XP  a| 
대상 포트가 있는 스토리지 배열의 하드웨어입니다.



 a| 
노드
 a| 
3-PAR를 참조하십시오
 a| 
호스트가 연결하는 포트가 포함된 스토리지 배열의 하드웨어 구성 요소입니다.



 a| 
FEBE 보드
 a| 
EMC Symmetrix입니다
 a| 



| 스토리지 프로세서(SP)  a| 
EMC CX, EMC VNX
 a| 



 a| 
LUN입니다
 a| 
다수의 스토리지 어레이
 a| 
하나 이상의 디스크 또는 디스크 파티션을 하나의 디스크 스토리지 공간으로 그룹화한 것입니다. ONTAP 설명서에서는 이것을 _array LUN_이라고 합니다.



 a| 
LDEV(LDEV
 a| 
Hitachi, HP XP입니다
 a| 



| LUN입니다  a| 
ONTAP
 a| 
ONTAP 시스템은 연결된 스토리지를 가상화하고 스토리지를 외부 애플리케이션 및 클라이언트에 대한 LUN으로 제공할 수 있습니다(예: iSCSI 및 FC를 통해). 클라이언트는 프런트엔드 LUN이 저장되는 위치를 인식하지 못합니다.



 a| 
LUN, 가상 디스크
 a| 
HP EVA(HP
 a| 
가상 디스크(사용자 인터페이스에서 _vDisk_라고 함)는 디스크 그룹에 생성된 시뮬레이션 디스크 드라이브입니다. 이름, 중복 수준 및 크기 같은 특성 조합을 가상 디스크에 할당할 수 있습니다. 가상 디스크를 제공하면 호스트에 스토리지를 제공합니다.



 a| 
어레이 LUN
 a| 
ONTAP 설명서, ONTAP 스토리지 관리 도구
 a| 
ONTAP 설명서에서는 _array LUN_이라는 용어를 사용하여 스토리지 시스템의 LUN과 프런트엔드 LUN(ONTAP LUN)을 구분합니다.



 a| 
VLUN을 선택합니다
 a| 
3PAR를 참조하십시오
 a| 
(volume-LUN) 가상 볼륨과 논리 유닛 번호(LUN) 간의 페어링 호스트에서 가상 볼륨을 보려면 스토리지 시스템에서 vLUN을 생성하여 볼륨을 LUN으로 내보내야 합니다.



 a| 
 a| 
|  


| 볼륨  a| 
ONTAP
 a| 
NFS(네트워크 파일 시스템), CIFS(Common Internet File System), HTTP(Hypertext Transfer Protocol), FC(파이버 채널), iSCSI(인터넷 SCSI)를 비롯하여 ONTAP에서 지원하는 하나 이상의 액세스 프로토콜을 통해 액세스할 수 있는 사용자 데이터를 저장하는 논리 엔터티입니다.



 a| 
가상 볼륨
 a| 
3PAR를 참조하십시오
 a| 
하나 이상의 논리 디스크에서 데이터를 매핑하여 생성한 가상 스토리지 유닛입니다.

|===