---
permalink: install/task_verifying_if_the_back_end_configuration_matches_the_expected_output.html 
sidebar: sidebar 
keywords: verify, back-end, configuration, matches, intended, configuration 
summary: 저장 장치 오류 표시로 감지된 백엔드 구성 오류를 해결한 후에는 기존 백엔드 구성이 의도한 구성과 일치하는지 확인하고 불일치로 인해 발생하는 문제를 해결해야 합니다. 
---
= 백엔드 구성이 의도된 구성과 일치하는지 확인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
에서 감지된 백엔드 구성 오류를 해결한 후에는 `storage errors show`기존 백엔드 구성이 의도한 구성과 일치하는지 확인하고 불일치로 인해 발생하는 문제를 해결해야 합니다.

.단계
. 다음 명령을 입력합니다. `storage array config show`
+
 `storage array config show`HA 쌍에 대한 다음 예제와 같이 스토리지 어레이별 LUN 그룹, LUN 수 및 경로에 대한 정보가 출력 그룹에 표시됩니다.

+
[listing]
----

mysystem1::> storage array config show
             LUN   LUN
Node         Group Count  Array Name      Array Target Port   Initiator
------------ ----- ----- ---------------  ------------------  ---------
mysystem1a    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
mysystem1b    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
8 entries were displayed.
----
.  `storage array config show`다음 표의 각 문제 설명에 대한 출력을 확인하고 해당 해결 방법을 참조하십시오.
+
|===
| 이 문제를 발견하면... | 다음 정보 보기... 


 a| 
LUN 그룹이 비어 있습니다
 a| 
xref:reference_reasons_for_no_luns_in_the_array_lun_group.adoc[스토리지 LUN 그룹에 LUN이 없는 이유]



 a| 
필요한 스토리지 어레이가 누락되었습니다
 a| 
xref:reference_reasons_storage_arrays_are_missing_from_command_output.adoc[예상한 모든 스토리지 어레이가 표시되지 않는 이유]



 a| 
스토리지 LUN 그룹이 예상보다 많습니다
 a| 
xref:reference_reasons_for_more_array_lun_groups_than_expected.adoc[스토리지 LUN 그룹이 예상보다 많은 이유]



 a| 
예상보다 적은 스토리지 LUN 그룹 수
 a| 
xref:reference_reasons_for_fewer_array_lun_groups_than_expected.adoc[스토리지 LUN 그룹 수가 예상보다 적은 이유]



 a| 
스토리지 LUN 그룹에 필요한 LUN 수가 표시되지 않습니다
 a| 
xref:reference_reasons_for_the_incorrect_number_of_luns_in_array_lun_groups.adoc[스토리지 LUN 그룹의 LUN 수가 잘못된 이유]



 a| 
예상보다 적은 경로
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[어레이 LUN에 대한 경로가 2개 미만입니다]



 a| 
예상보다 많은 경로
 a| 
xref:reference_reasons_for_more_paths_to_an_array_lun_than_expected.adoc[스토리지 LUN에 대한 경로가 예상보다 많은 이유]

|===

