---
permalink: install/task_displaying_target_port_queue_depth_statistics_clustered_data_ontap_8_2_and_later.html 
sidebar: sidebar 
keywords: display, target, queue, depth, statistics 
summary: 대상 큐 길이 설정으로 인해 스토리지 배열의 성능 문제가 발생하는 것으로 의심되는 경우 대기열 길이에 대해 설정된 값을 확인하고 FC 이니시에이터 포트의 요청 상태를 확인해야 합니다. 
---
= 타겟 큐 길이 통계 표시
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대상 큐 길이 설정으로 인해 스토리지 배열의 성능 문제가 발생하는 것으로 의심되는 경우 대기열 길이에 대해 설정된 값을 확인하고 FC 이니시에이터 포트의 요청 상태를 확인해야 합니다.

대상 포트에서 요청을 처리하는 데 문제가 있는지 여부를 확인하기 위해 액세스할 수 있는 다양한 수준의 세부 정보가 있습니다. 다음 단계에서는 대상 포트 대기열 깊이에 대한 현재 설정을 확인하고, 포트에서 대기 중인 요청이 있는지 여부를 확인하고, 포트의 작업 부하를 이해하는 데 도움이 되는 자세한 포트 통계를 표시하는 방법을 설명합니다.

.단계
. 명령을 매개 변수와 함께 사용하여 `storage array show` `-instance` 대상 포트 큐 깊이의 현재 값을 표시합니다.
+
[listing]
----
> set advanced
> storage array show -instance

Name: HP2
                 Prefix: HP-2
                 Vendor: HP
                  Model: HSV300
                options:
          Serial Number: 50014380025d1500
Target Port Queue Depth: 512
        LUN Queue Depth: 32
        Upgrade Pending: false
    Optimization Policy: eALUA
               Affinity: aaa
             Error Text: -
----
. 명령을 사용하여 `storage array port show -fields max-queue-depth` 스토리지 배열의 각 포트에 대한 큐 길이 설정을 표시합니다.
+
[listing]
----
> set advanced
> storage array port show -fields max-queue-depth

name            wwnn             wwpn             max-queue-depth
--------------- ---------------- ---------------- ---------------
EMC_SYMMETRIX_1 50060480000001a0 50060480000001a0 -
EMC_SYMMETRIX_1 50060480000001a1 50060480000001a1 -
EMC_SYMMETRIX_1 50060480000001b0 50060480000001b0 -
EMC_SYMMETRIX_1 50060480000001b1 50060480000001b1 256
----
+
""-" `Max Queue Depth` 값은 포트에 특정 최대 대기열 길이 설정이 없으며 스토리지 배열 수준에서 설정된 값을 사용하고 있음을 나타냅니다.

. 명령을 사용하여 `storage array port show` 스토리지 배열 대상 포트에 대한 성능 정보를 표시합니다.
+
이 명령의 결과는 포트와 관련된 성능 문제가 있는지 여부를 확인하는 데 도움이 됩니다.  `%busy` `%waiting` 및 값은 포트 성능에 대한 상위 수준의 뷰를 제공합니다. 이러한 값이 처리 대기 중인 요청의 비율이 높거나 포트가 많은 시간 동안 사용 중임을 나타내는 경우 포트 상태를 자세히 조사해야 할 수 있습니다.

+
[listing]
----

vgv3070f51::*> storage array port show

Array Name: HP2
WWNN: 50014380025d1500
WWPN: 50014380025d1508
Connection Type: fabric
Switch Port: vgbr300s70:9
Link Speed: 4   GB/s
Max Queue Depth: -
                              LUN                                 Link
Node       Initiator  Count   IOPS    KB/s    %busy    %waiting   Errs
---------  ---------  -----  ------  ------  -------  ----------  ----
vgv51-02       0a     21       2      53        0           0     0
vgv51-01       0a     21       2      48        1           0     0
----
. 명령을 , , , 또는 필드 와 함께 사용하면 포트에 대한 자세한 정보를 얻을 수 `storage array port show -fields` `average-latency-per-iop` `average-pending` `average-waiting` `max-pending` `max-waiting` 있습니다.

