---
permalink: implement-third-party/reference_required_parameters_for_3par_arrays_with_data_ontap_systems.html 
sidebar: sidebar 
keywords: required, parameters, 3par, arrays, ontap, systems, host, persona, settings, port, 
summary: 스토리지 배열이 ONTAP 시스템에서 성공적으로 작동하려면 스토리지 배열에서 특정 매개 변수 설정이 필요합니다. 
---
= ONTAP 시스템을 사용한 3PAR 어레이의 필수 매개 변수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열이 ONTAP 시스템에서 성공적으로 작동하려면 스토리지 배열에서 특정 매개 변수 설정이 필요합니다.



== 호스트 사용자 설정

펌웨어 2.3.1 이상이 설치된 3PAR 스토리지의 경우 다음 표와 같이 필수 호스트 사용자 값을 설정해야 합니다.

|===
| 연결 유형 | 호스트 페르소나 


 a| 
직접 연결
 a| 
10



 a| 
패브릭 연결
 a| 
10

|===
3PAR 스토리지 시스템에 ONTAP 시스템을 연결하기 위해 스위치를 조닝하기 전에 3PAR 스토리지 시스템에 필요한 호스트 정의를 생성해야 합니다. 호스트 정의 전에 조닝이 구성된 경우 ONTAP은 3PAR LUN을 LUN 254 및 ONTAP에서 사용할 수 없는 제품 유형 SES로 검색합니다. 그 결과 새로 매핑된 3PAR LUN을 ONTAP 시스템에 할당할 수 없으며, ONTAP에 3PAR LUN 대신 LUN 254가 표시되기 때문에 애그리게이트에 이미 추가되었을 수 있는 일부 3PAR LUN을 사용할 수 없습니다. 이 문제가 발생할 경우 ONTAP는 다음과 같은 EMS 메시지를 생성한다.

[listing]
----
mlm.array.unknown:warning - Array LUN XXXXXXXX.126L254 [S/N 'XXXXXXX' vendor '3PARdata' product 'SES'] is unknown and is not supported in this version of Data ONTAP.
----
호스트 정의 전에 조닝을 구성한 경우 경로 재초기화를 수행하여 3PAR 스토리지 어레이에서 매핑된 어레이 LUN을 강제로 재검색함으로써 문제를 해결할 수 있습니다. 이 문제에 대한 해결 방법은 3PAR 스토리지 배열의 알 수 없는 장치(L254/SES) 문제에 대한 해결 방법 섹션을 참조하십시오.

xref:reference_workaround_for_the_unknown_device_l254_ses_problem_with_3par_storage_arrays.adoc[3PAR 스토리지 어레이의 알 수 없는 디바이스(L254/SES) 문제에 대한 해결 방법입니다]



== 포트 사용자 설정

펌웨어 2.2.x를 사용하는 3PAR 스토리지의 경우 다음 표에 나와 있는 대로 필요한 포트 사용자 값을 설정해야 합니다.

|===
| 연결 유형 | 포트 페르소나 


 a| 
직접 연결
 a| 
18



 a| 
패브릭 연결
 a| 
19

|===