---
permalink: implement-third-party/reference_workaround_for_the_unknown_device_l254_ses_problem_with_3par_storage_arrays.html 
sidebar: sidebar 
keywords: 'Workaround, unknown device (l254/ses), problem, 3PAR, storage, arrays, aggregates, luns, created, ontap system, not' 
summary: 3PAR 스토리지 시스템에서 ONTAP 시스템을 사용하는 3PAR 스토리지의 필수 매개 변수 섹션에 지정된 호스트 정의를 3PAR 스토리지 시스템에 생성해야 ONTAP 시스템을 3PAR 스토리지에 연결할 수 있습니다. 호스트 정의 전에 조닝이 구성된 경우 ONTAP은 3PAR 어레이 LUN을 LUN 254 및 ONTAP에서 사용할 수 없는 제품 유형 SES를 검색합니다. 
---
= 3PAR 스토리지 어레이의 알 수 없는 디바이스(L254/SES) 문제에 대한 해결 방법입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
3PAR 스토리지 시스템에서 ONTAP 시스템을 사용하는 3PAR 스토리지의 필수 매개 변수 섹션에 지정된 호스트 정의를 3PAR 스토리지 시스템에 생성해야 ONTAP 시스템을 3PAR 스토리지에 연결할 수 있습니다. 호스트 정의 전에 조닝이 구성된 경우 ONTAP은 3PAR 어레이 LUN을 LUN 254 및 ONTAP에서 사용할 수 없는 제품 유형 SES를 검색합니다.

xref:reference_required_parameters_for_3par_arrays_with_data_ontap_systems.adoc[ONTAP 시스템을 사용한 3PAR 어레이의 필수 매개 변수]

ONTAP가 3PAR 어레이 LUN을 LUN 254 및 제품 유형 SES로 검색하면 새로 매핑된 3PAR LUN을 ONTAP 시스템에 할당할 수 없으며, ONTAP에 LUN 254가 표시되므로 이미 애그리게이트에 추가되었을 수 있는 일부 3PAR LUN을 사용할 수 없습니다. ONTAP는 LUN 254로 검색된 LUN에 대해 EMS 메시지를 생성하고 일부 LUN을 알 수 없는 디바이스로 보고합니다.

호스트 정의 전에 조닝을 구성한 경우 3PAR 스토리지 어레이에서 매핑된 스토리지 LUN을 강제로 다시 검색함으로써 LUN 254/SES 알 수 없는 디바이스 문제를 해결할 수 있습니다. 3PAR 어레이 LUN을 사용한 애그리게이트가 ONTAP 시스템에 이미 구성되어 있는지 여부에 따라 사용되는 절차가 달라집니다. (다음 절차에서는 노드 1과 노드 2가 ONTAP 노드의 이름이라고 가정합니다.)



== 3PAR 어레이 LUN을 사용하는 애그리게이트가 ONTAP 시스템에 이미 생성된 경우

. 다음 명령을 실행하여 ONTAP 시스템에서 HA 구성이 사용되도록 *`cluster ha show`설정하십시오. *
+
다음 출력이 표시됩니다.

+
[listing]
----

High Availability Configured: true
----
. 다음 명령을 실행하여 스토리지 페일오버가 ONTAP 시스템에 구성되어 있는지 *`storage failover show`확인하십시오. *
+
다음 출력이 표시됩니다.

+
[listing]
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-1    Node-2    true     Connected to Node-2
Node-2    Node-1    true     Connected to Node-1
2 entries were displayed.
----
. 다음 명령을 실행하여 노드 1에 대해 테이크오버 작업을 수행합니다 *`storage failover takeover -ofnode Node-1`. *
. 다음 명령을 다시 실행하여 노드-2가 반환 작업을 수행할 준비가 되었는지 *`storage failover show`확인합니다. *
+
다음 출력이 표시됩니다.

+
[listing]
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-2    Node-1    false    In takeover, Auto giveback will be
                                      initiated in 348 seconds
Node-1    Node-2    -        Waiting for giveback (HA mailboxes)
2 entries were displayed.
----
. 다음 명령을 실행하여 노드 1에 대한 반환 작업을 *`storage failover giveback -ofnode Node-1 -require-partner-waiting true`수행합니다. *
. 클러스터의 다른 노드에서 3단계부터 5단계까지 반복합니다.




== 3PAR 어레이 LUN을 사용하는 애그리게이트가 ONTAP 시스템에서 생성되지 않은 경우

. 다음 명령을 실행하여 3PAR 스토리지 어레이에 접속된 모든 ONTAP FC 이니시에이터 포트를 나열합니다 *`system node run -node <node name> -command "sysconfig -v"`. *
+
다음 예제는 * 포함된 특정 노드 이름을 가진 명령을 보여줍니다 *`system node run -node Node-1 -command "sysconfig -v"`

. 다음 명령을 실행하여 나열된 모든 포트를 오프라인으로 전환합니다 *`system node run -node <node name> -command "priv set advanced;fcadmin offline <adapter>"`.*
+
다음 예는 특정 노드 이름과 어댑터가 포함된 명령을 보여줍니다 *`system node run -node Node-1 -command "priv set advanced;fcadmin offline 0a"`. *

. 다음 명령을 실행하여 나열된 모든 포트를 온라인 상태로 전환합니다 *`system node run -node <node name> -command "priv set advanced;fcadmin online <adapter>"`.*
+
다음 예는 특정 노드 이름과 어댑터가 포함된 명령을 보여줍니다 *`system node run -node Node-1 -command "priv set advanced;fcadmin online 0a"`. *


