---
permalink: implement-third-party/task_preparing_hp_eva_storage_arrays_for_ndu.html 
sidebar: sidebar 
keywords: prepare, hp, eva, storage, arrays, ndu 
summary: HP EVA 스토리지 어레이는 펌웨어 업그레이드 중에 대상 포트를 오프라인으로 전환하는 경향이 있습니다. ONTAP에서는 펌웨어 업그레이드 중에 타겟 포트가 오프라인 상태가 되는 경우 ONTAP 시스템이 중단되지 않도록 ONTAP 복원력을 높이는 명령을 제공합니다. 이 명령은 ONTAP를 실행하는 스토리지 시스템에서만 사용할 수 있습니다. 
---
= NDU를 위해 HP EVA 스토리지 어레이 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HP EVA 스토리지 어레이는 펌웨어 업그레이드 중에 대상 포트를 오프라인으로 전환하는 경향이 있습니다. ONTAP에서는 펌웨어 업그레이드 중에 타겟 포트가 오프라인 상태가 되는 경우 ONTAP 시스템이 중단되지 않도록 ONTAP 복원력을 높이는 명령을 제공합니다. 이 명령은 ONTAP를 실행하는 스토리지 시스템에서만 사용할 수 있습니다.

HP에서 제공하는 로드 권장 사항(HP EVA)에 대한 지침을 포함하여 펌웨어 업그레이드 수행에 대한 지침을 따라야 합니다. HP가 지원하는 펌웨어로만 업그레이드할 수 있습니다. 이 절차는 HP EVA 펌웨어 업그레이드 TYPE_ONLINE 업그레이드 _ 에 적용됩니다.

[NOTE]
====
펌웨어를 업그레이드하는 동안 두 HP EVA 컨트롤러가 모두 재부팅됩니다.

====
이 절차에서는 ONTAP 명령을 사용하여 펌웨어 업그레이드 전반에 걸쳐 ONTAP의 복원력을 높입니다. 펌웨어 업그레이드가 완료되면 ONTAP 명령을 다시 사용하여 포트를 정상 작동 모드로 되돌립니다.

.단계
. ONTAP 시스템에서 명령 세션의 권한 수준을 advanced: * 로 설정합니다 *`set -privilege advanced`
. 펌웨어 업그레이드를 진행 중인 HP EVA 스토리지 어레이에 대해 매개 변수를 * true * 로 설정합니다 `is-upgrade-pending` *`storage array modify -name array_name -is-upgrade-pending true`
. 스토리지 배열에서 펌웨어 업그레이드를 시작합니다.
. 펌웨어 업그레이드가 완료된 후 필요한 경우 권한 수준을 다시 Advanced로 설정한 다음, ONTAP 시스템에서 `is-upgrade-pending` 매개 변수를 * false * 로 설정하여 스토리지 어레이 포트를 정상 작동 상태로 되돌립니다. *`storage array modify -name array_name -is-upgrade-pending false`*
+
2단계에서 고급 모드를 종료하지 않은 경우 다시 액세스할 필요가 없습니다.

+
매개 변수에는 `is-upgrade-pending` 명령을 올바르게 사용할 수 있도록 다음 기능이 포함되어 있습니다.

+
** 스토리지 배열에서 업그레이드가 진행되는 동안 * FALSE * 로 설정하려고 하면 `is-upgrade-pending` 명령이 실패하고 EMS 메시지가 반환됩니다.
** true * 로 설정된 시점부터 60분 이내에 * false * 로 상태가 반환되지 않으면 `is-upgrade-pending` EMS 메시지는 * false * 로 반환될 때까지 1시간마다 `is-upgrade-pending` 기록됩니다.



